name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: [self-hosted, linux, X64]

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: podman build . --file Dockerfile --tag kosalaat/myalpinenginx:$(date +%s)
