name: Test build of the docker image

on: 
  branch: [ feature-* ]

  
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - nmae: Docker build
        run: docker build . --tag test-build
